name: WenjaPvPHCF
version: 1.1-RELEASE
description: "Custom HCFCore Forked by Gender"
author: DoctorDark, Mason
main: server.wenjapvp.hcf.HCF
softdepend: [ProtocolLib]
commands:
  spawn:
  enderdragon:
  hub:
  this:
  playtime:
  cobble:
  staffinfo:
      aliases: [staffbaninfo]
  crowgive:
     aliases: [crowbar, crowbargive]
  wenja:
  hcfhelp:
      aliases: [help, ehelp]
  conquest:
    description: command used to handle conquest events.
  economy:
    aliases: [$, bal, money, eco, econ]
    description: command used to modify the economy.
  eotw:
    aliases: [endoftheworld]
    description: sets if the server is in end of the world mode.
  event:
    description: command used to manage minigame events.
  faction:
    aliases: [f, fac]
    description: faction related commands.
  gopple:
    description: command to check remaining op apple cooldown time.
    aliases: [opple, goppletimer, goppletime, oppletimer, oppletime]
  hcf:
    aliases: [hardcorefactions, hcfactions]
  koth:
    description: make or delete koth arenas.
  lives:
    description: management of lives or deathbans.
  location:
    aliases: [loc]
    description: check the faction location of a player.
  logout:
    aliases: [disconnect]
    description: command to safely logout without an npc spawning.
  mapkit:
    aliases: [viewkit]
    description: used to check the current map restrictions.
  pay:
    aliases: [p2p]
    description: allow players to pay money.
  pvptimer:
    aliases: [pvp]
    description: command to enable or disable pvp timer protection.
  regen:
    description: check eta until a faction is able to regenerate dtr.
  servertime:
    description: checks the date and time of server.
  sotw:
    aliases: [startoftheworld]
    description: command used to manage start of the world.
  spawncannon:
    aliases: [cannon, playercannon]
    description: shoots you into the warzone.
  staffrevive:
    description: command used by staff to revive players.
  timer:
    description: command to manage timers.
  togglebroadcasts:
    aliases: [tb]
    description: toggle found diamond ore notifications.
  togglecapzoneentry:
    aliases: [togglecapentry]
    description: command used to hide or show capture zone entry messages.
  togglelightning:
    aliases: [lightningtoggle, togglestrikes]
    description: toggles the lightning strikes for when a player dies.
  togglesidebar:
    aliases: [sidebartoggle, sidebar, hud, togglehud]
    description: toggles the scoreboard timers displayed on sidebar.